### PR TITLE
Add section about how to use it in Mac

### PR DESCRIPTION
**Pull request by milochen0418**
Thanks Brahim Jarrar to create the nice project and share to everyone !
I love it !  

I'm a Mac user who love coding everywhere and need internet.  
When I find out I cannot use this project in Mac, I tried to solve it.
I have solve this problem and I want to contribute this information to WIFI-Brute-Force project. 

The following is what WIFI-Brute-Force work on my Mac  

Screen Shot 2019-09-21 at 2 21 32 AM

### CODE REVIEW

**Comment by anouarbensaad** [comment]
Hi milochen0418

It's not a OS problem but the problem from the smaller passlist,
use crunch to generate passwords list ,
Maybe he can help you.

**Comment by milochen0418** [comment]
I have no problem like you in any platform.

Mac cannot use this project  because the dependent package  pywifi is not support for Mac . 

so , we are process in different problem. 
Am I right ?  

thanks :) 
-----Original message-----

**Comment by madeyexz** [comment]
Thanks for the amazing tool first!

But i encountered an error when i was trying to use it on my macOS
It says: "Profile" is not defined
image

Can you help me solve it?

**Comment by Squuv** [comment]
thanks!

**Comment by milochen0418** [comment]
I saw it :D 
https://github.com/Squuv/WifiBF/commit/e103ac2fd0635353b2aee5b1b1b66823e1900b39
You're welcome :D nice work

**Pull request closed without merging**
